### ISSUE TITLE
please add zenodo publication to Global Biotic Interactions zenodo community

### ISSUE THREAD

**Issue by jhpoelen** [millerse/Arctic-food-web#1]
Hi! I noticed that this dataset has been published to zenodo, but not yet added to the Global Biotic Interaction community. Could you please review this (and other) datasets and make sure that you request to be added to the community? See https://github.com/jhpoelen/eol-globi-data/wiki/Dataset-Management .

**Comment by millerse** [comment]
Doing that now.

**Comment by jhpoelen** [comment]
@millerse please let me know if there's anything I can do to help

**Comment by jhpoelen** [comment]
Thanks for adding your datasets to Zenodo's Global Biotic Interactions community! You've contributed a serious amount of datasets: it took me quite a while to accept all your requests.
